# Generated by Django 4.2.11 on 2026-05-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0185_gfk_indexes'),
        ('meu_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('latency', models.CharField(max_length=50)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
            ],
            options={
                'verbose_name': 'Device Monitor',
            },
        ),
        migrations.DeleteModel(
            name='Exemplo',
        ),
    ]
